# Inserts a blank line between shell prompts
add_newline = true

# Replace the '❯' symbol in the prompt with '➜'
[character] 
success_symbol = '[➜](bold green)'

# 'bold red' style and discharging_symbol when capacity is between 0% and 10%
[[battery.display]]
threshold = 20
style = 'bold red'

[cmd_duration]
min_time = 1
format = 'took [$duration](bold yellow)'

[directory]
truncation_length = 1000
truncate_to_repo = false
use_os_path_sep = true
truncation_symbol = '…/'

[git_branch]
always_show_remote = true

[git_commit]
commit_hash_length = 7




